name: Build and Deploy

on:
  push:
    branches: [main]

env:
  REGISTRY: gitea.lobster-hake.ts.net
  IMAGE_NAME: lanos-familia/scottlanoue-site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Trigger Nomad redeploy
        run: |
          # Force Nomad to pull the new image by updating the job
          curl -s -X POST \
            -H "Authorization: Bearer ${{ secrets.NOMAD_TOKEN }}" \
            "${{ secrets.NOMAD_ADDR }}/v1/job/scottlanoue-site/periodic/force" || \
          curl -s -X DELETE \
            -H "Authorization: Bearer ${{ secrets.NOMAD_TOKEN }}" \
            "${{ secrets.NOMAD_ADDR }}/v1/job/scottlanoue-site/allocations" || true
          echo "Triggered redeploy"
